version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/